package api

import (
	"encoding/json"
	"io/fs"
	"net/http"
	"strings"

	"github.com/CFM503/goPass/internal/config"
	"github.com/CFM503/goPass/internal/engine"
	"github.com/CFM503/goPass/web"
)

type Server struct{engine *engine.Engine}

func StartServer(addr string,eng *engine.Engine)error{s:=&Server{engine:eng};mux:=http.NewServeMux();subFS,err:=fs.Sub(web.FS,".");if err!=nil{return err};mux.Handle("/",http.FileServer(http.FS(subFS)));mux.HandleFunc("/api/status",s.handleStatus);mux.HandleFunc("/api/settings",s.handleSettings);mux.HandleFunc("/api/upstream",s.handleUpstream);mux.HandleFunc("/api/performance",s.handlePerformance);mux.HandleFunc("/api/process-whitelist",s.handleProcessWhitelist);return http.ListenAndServe(addr,mux)}

func(s *Server)handleStatus(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","application/json");if r.Method!=http.MethodGet{http.Error(w,"method not allowed",405);return};pid,conns:=0,0;statuses:=[]engine.ProcessStatus{};if s.engine!=nil&&s.engine.Stats!=nil{pid,conns=s.engine.Stats.PID,s.engine.Stats.Connections;statuses=s.engine.GetProcessStatuses()};proxyPrograms,directPrograms,proxyConnections,directConnections:=0,0,0,0;for _,p:=range statuses{if p.Status=="proxy"{proxyPrograms++;proxyConnections+=p.Connections}else{directPrograms++;directConnections+=p.Connections}};_=json.NewEncoder(w).Encode(map[string]interface{}{"status":"running","pid":pid,"connections":conns,"proxy_programs":proxyPrograms,"direct_programs":directPrograms,"proxy_connections":proxyConnections,"direct_connections":directConnections,"processes":statuses})}

func(s *Server)handleSettings(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","application/json");if r.Method==http.MethodGet{ws,limit:=5,20;if s.engine!=nil{c:=s.engine.GetConfig();ws,limit=c.API.WSRefreshInterval,c.API.UIConnLimit};_=json.NewEncoder(w).Encode(map[string]interface{}{"ws_refresh_interval":ws,"ui_conn_limit":limit});return};if r.Method!=http.MethodPost{http.Error(w,"method not allowed",405);return};var req struct{WSRefreshInterval int `json:"ws_refresh_interval"`;UIConnLimit int `json:"ui_conn_limit"`};if err:=json.NewDecoder(r.Body).Decode(&req);err!=nil{http.Error(w,"invalid request",400);return};if s.engine!=nil{s.engine.UpdateUIConfig(req.WSRefreshInterval,req.UIConnLimit);_=s.engine.SaveConfig("config.json")};_=json.NewEncoder(w).Encode(map[string]interface{}{"status":"ok"})}

func(s *Server)handlePerformance(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","application/json");if s.engine==nil{http.Error(w,"engine not ready",503);return};if r.Method==http.MethodGet{p:=s.engine.GetConfig().Performance;_=json.NewEncoder(w).Encode(map[string]interface{}{"buffer_size":config.ClampBufferSize(p.BufferSize)});return};if r.Method!=http.MethodPost{http.Error(w,"method not allowed",405);return};var req struct{BufferSize int `json:"buffer_size"`};if err:=json.NewDecoder(r.Body).Decode(&req);err!=nil{http.Error(w,"invalid request",400);return};size:=config.ClampBufferSize(req.BufferSize);p:=s.engine.GetConfig().Performance;p.BufferSize=size;s.engine.UpdatePerformance(p);if err:=s.engine.SaveConfig("config.json");err!=nil{http.Error(w,"save failed",500);return};_=json.NewEncoder(w).Encode(map[string]interface{}{"status":"ok","buffer_size":size})}

func(s *Server)handleUpstream(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","application/json");if r.Method==http.MethodGet{var t,a string;var p int;if s.engine!=nil{var c=*s.engine.GetConfig();if len(c.Outbounds.Servers)>0{x:=c.Outbounds.Servers[0];t,a,p=x.Type,x.Address,x.Port}};_=json.NewEncoder(w).Encode(map[string]interface{}{"type":t,"address":a,"port":p});return};if r.Method==http.MethodPost{var req struct{Type string `json:"type"`;Address string `json:"address"`;Port int `json:"port"`};if err:=json.NewDecoder(r.Body).Decode(&req);err==nil&&s.engine!=nil&&(req.Type=="socks5"||req.Type=="http")&&strings.TrimSpace(req.Address)!=""&&req.Port>=1&&req.Port<=65535{s.engine.UpdateUpstream(req.Type,strings.TrimSpace(req.Address),req.Port,"config.json");_=json.NewEncoder(w).Encode(map[string]interface{}{"status":"ok"});return}};http.Error(w,"invalid request",400)}

func(s *Server)handleProcessWhitelist(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","application/json");if s.engine==nil{http.Error(w,"engine not ready",503);return};switch r.Method{case http.MethodGet:_=json.NewEncoder(w).Encode(map[string]interface{}{"processes":s.engine.GetProcessWhitelist()});case http.MethodPost:var req struct{Process string `json:"process"`};if err:=json.NewDecoder(r.Body).Decode(&req);err!=nil||strings.TrimSpace(req.Process)==""{http.Error(w,"process is required",400);return};list:=append(s.engine.GetProcessWhitelist(),req.Process);s.engine.UpdateProcessWhitelist(list,"config.json");_=json.NewEncoder(w).Encode(map[string]interface{}{"status":"ok","processes":s.engine.GetProcessWhitelist()});case http.MethodDelete:var req struct{Process string `json:"process"`};if err:=json.NewDecoder(r.Body).Decode(&req);err!=nil||strings.TrimSpace(req.Process)==""{http.Error(w,"process is required",400);return};old:=s.engine.GetProcessWhitelist();list:=make([]string,0,len(old));for _,p:=range old{if !strings.EqualFold(p,req.Process){list=append(list,p)}};s.engine.UpdateProcessWhitelist(list,"config.json");_=json.NewEncoder(w).Encode(map[string]interface{}{"status":"ok","processes":s.engine.GetProcessWhitelist()});default:http.Error(w,"method not allowed",405)}}
