let uiConnLimit=20, pollTimer=null;
function $(id){return document.getElementById(id)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||''))}
function init(){bindNav();bindActions();loadSettings();loadUpstream();loadPerformance();loadProcesses();refreshStatus();pollTimer=setInterval(refreshStatus,2000)}
function bindNav(){const views={status:'view-status',processes:'view-processes',settings:'view-settings'},nav={status:'nav-status',processes:'nav-processes',settings:'nav-settings'};for(const k of Object.keys(nav))$(nav[k])?.addEventListener('click',e=>{e.preventDefault();for(const x of Object.keys(nav)){$(nav[x])?.classList.toggle('active',x===k);$(views[x]).style.display=x===k?'block':'none'};$('page-title').textContent=k==='status'?'代理 / 直连状态':k==='processes'?'进程白名单':'设置';if(k==='processes')loadProcesses();if(k==='settings'){loadUpstream();loadPerformance()}history.replaceState(null,'',`#${k}`)})}
function bindActions(){$('add-process-btn')?.addEventListener('click',addProcess);$('process-input')?.addEventListener('keydown',e=>{if(e.key==='Enter')addProcess()});$('save-settings-btn')?.addEventListener('click',saveSettings)}
async function json(url,options){const r=await fetch(url,options);if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function refreshStatus(){try{const d=await json('/api/status');$('sys-pid').textContent=d.pid??'--';$('proxy-programs').textContent=d.proxy_programs??0;$('direct-programs').textContent=d.direct_programs??0;$('proxy-connections').textContent=d.proxy_connections??0;$('direct-connections').textContent=d.direct_connections??0;setEngineState(d.status==='running');renderStatuses(Array.isArray(d.processes)?d.processes:[])}catch(e){setEngineState(false)}}
function setEngineState(ok){$('engine-status').classList.toggle('green',ok);$('engine-status').classList.toggle('red',!ok);$('engine-status-text').textContent=ok?'运行中':'未连接'}
function renderStatuses(list){const body=$('process-status-list');const rows=($('active-only')?.checked!==false)?list.filter(x=>Number(x.connections)>0):list;if(!rows.length){body.innerHTML='<tr><td colspan="5" class="empty">当前没有检测到活动网络连接。</td></tr>';return}rows.sort((a,b)=>Number(b.connections||0)-Number(a.connections||0));body.innerHTML=rows.map(x=>{const proxy=x.status==='proxy';const targets=Array.isArray(x.targets)&&x.targets.length?x.targets.map(esc).join('<br>'):'-';return `<tr><td><strong>${esc(x.process)}</strong></td><td>${esc(x.pid)}</td><td><span class="state ${proxy?'proxy':'direct'}">${proxy?'代理':'直连'}</span></td><td>${esc(x.connections)}</td><td class="targets">${targets}</td></tr>`}).join('')}
async function loadSettings(){try{const d=await json('/api/settings');uiConnLimit=Math.max(1,Number(d.ui_conn_limit||20))}catch(e){}}
async function loadUpstream(){try{const d=await json('/api/upstream');$('upstream-type').value=d.type||'socks5';$('upstream-addr').value=d.address||'127.0.0.1';$('upstream-port').value=d.port||9192}catch(e){}}
async function loadPerformance(){try{const d=await json('/api/performance');const n=Math.min(1048576,Math.max(32768,Number(d.buffer_size||262144)));$('relay-buffer-size').value=String(n)}catch(e){}}
async function loadProcesses(){try{const d=await json('/api/process-whitelist');renderProcesses(Array.isArray(d.processes)?d.processes:[])}catch(e){$('process-list').innerHTML=''}}
function renderProcesses(list){const box=$('process-list'),empty=$('process-empty');if(!list.length){box.innerHTML='';empty.style.display='block';return}empty.style.display='none';box.innerHTML=list.map(p=>`<div class="process-item"><strong>${esc(p)}</strong><button class="danger" onclick="removeProcess('${esc(p)}')">删除</button></div>`).join('')}
async function addProcess(){const input=$('process-input'),p=input?.value.trim();if(!p)return;try{const d=await json('/api/process-whitelist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({process:p})});input.value='';renderProcesses(d.processes||[]);refreshStatus()}catch(e){alert('添加失败：'+e.message)}}
window.removeProcess=async function(p){try{const d=await json('/api/process-whitelist',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({process:p})});renderProcesses(d.processes||[]);refreshStatus()}catch(e){alert('删除失败：'+e.message)}};
async function saveSettings(){const btn=$('save-settings-btn'),msg=$('settings-save-msg');const type=$('upstream-type').value,address=$('upstream-addr').value.trim(),port=Number($('upstream-port').value),buffer=Math.min(1048576,Math.max(32768,Number($('relay-buffer-size').value||262144)));if(!address||port<1||port>65535){alert('请输入有效的代理地址和端口');return}btn.disabled=true;btn.textContent='保存中...';try{const ru=await json('/api/upstream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,address,port})});if(ru.status!=='ok')throw new Error('代理设置保存失败');const rp=await json('/api/performance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({buffer_size:buffer})});if(rp.status!=='ok')throw new Error('Buffer 设置保存失败');$('relay-buffer-size').value=String(rp.buffer_size||buffer);msg.style.display='inline';setTimeout(()=>msg.style.display='none',2500)}catch(e){alert('保存失败：'+e.message)}finally{btn.disabled=false;btn.textContent='保存设置'}}
document.addEventListener('DOMContentLoaded',init);
