let uiConnLimit=20, domCache=null;
function $(id){return document.getElementById(id)}
function getDOM(){if(domCache)return domCache;return domCache={sysPid:$('sys-pid'),connCount:$('conn-count'),rx:$('rx-bytes'),tx:$('tx-bytes'),connBody:$('conn-list-proxy')}}
document.addEventListener('DOMContentLoaded',()=>{bindNav();loadSettings();loadUpstream();loadPerformance();loadProcesses();connectWS();$('add-process-btn')?.addEventListener('click',addProcess);$('process-input')?.addEventListener('keydown',e=>{if(e.key==='Enter')addProcess()});$('save-settings-btn')?.addEventListener('click',saveSettings)});
function bindNav(){const views={dashboard:'view-dashboard',processes:'view-processes',settings:'view-settings'};const nav={dashboard:'nav-dashboard',processes:'nav-processes',settings:'nav-settings'};for(const k of Object.keys(nav))$(nav[k])?.addEventListener('click',e=>{e.preventDefault();for(const x of Object.keys(nav)){$(nav[x])?.classList.toggle('active',x===k);$(views[x]).style.display=x===k?'block':'none'};$('page-title').innerText=k==='dashboard'?'TCP Proxy Overview':k==='processes'?'Proxy Processes':'Settings';if(k==='processes')loadProcesses()})}
function connectWS(){const s=new WebSocket(`ws://${location.host}/ws`);s.onopen=()=>setStatus(true);s.onmessage=e=>{try{const d=JSON.parse(e.data),o=getDOM();o.sysPid.innerText=d.pid??0;o.connCount.innerText=d.connections??0;o.rx.innerText=d.rx||'0 B/s';o.tx.innerText=d.tx||'0 B/s';renderConnections(Array.isArray(d.active)?d.active:[])}catch(err){console.error(err)}};s.onclose=()=>{setStatus(false);setTimeout(connectWS,3000)};s.onerror=()=>s.close()}
function setStatus(ok){const e=$('engine-status');if(e){e.classList.toggle('green',ok);e.classList.toggle('red',!ok)}}
function renderConnections(c){const list=c.slice(0,uiConnLimit);const b=getDOM().connBody;b.innerHTML=list.length?list.map(x=>`<tr><td>${esc(x.id||'')}</td><td>${esc(x.target||'')}</td></tr>`).join(''):'<tr><td colspan="2">No active proxied connections.</td></tr>'}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function loadSettings(){fetch('/api/settings').then(ok).then(d=>{$('ws-interval').value=d.ws_refresh_interval||5;$('ui-conn-limit').value=d.ui_conn_limit||20;uiConnLimit=Math.max(1,Number(d.ui_conn_limit||20))}).catch(console.error)}
function loadUpstream(){fetch('/api/upstream').then(ok).then(d=>{$('upstream-type').value=d.type||'socks5';$('upstream-addr').value=d.address||'';$('upstream-port').value=d.port||9192}).catch(console.error)}
function loadPerformance(){fetch('/api/performance').then(ok).then(d=>{$('relay-buffer-size').value=String(Math.min(1048576,Math.max(32768,Number(d.buffer_size||262144))))}).catch(console.error)}
function loadProcesses(){fetch('/api/process-whitelist').then(ok).then(d=>renderProcesses(Array.isArray(d.processes)?d.processes:[])).catch(console.error)}
function renderProcesses(list){const box=$('process-list'),empty=$('process-empty');empty.style.display=list.length?'none':'block';box.innerHTML=list.map(p=>`<div style="display:flex;justify-content:space-between;align-items:center;padding:10px;margin:8px 0;background:rgba(255,255,255,.05);border-radius:5px"><strong>${esc(p)}</strong><button onclick="removeProcess('${esc(p)}')" style="padding:5px 10px;background:rgba(255,50,50,.2);border:1px solid rgba(255,50,50,.5);color:#fff;border-radius:4px;cursor:pointer">Remove</button></div>`).join('')}
async function addProcess(){const input=$('process-input');const p=input?.value.trim();if(!p)return;try{const r=await fetch('/api/process-whitelist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({process:p})});if(!r.ok)throw new Error(await r.text());input.value='';const d=await r.json();renderProcesses(d.processes||[])}catch(e){console.error(e);alert('Failed to add process')}}
window.removeProcess=async function(p){try{const r=await fetch('/api/process-whitelist',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({process:p})});if(!r.ok)throw new Error(await r.text());const d=await r.json();renderProcesses(d.processes||[])}catch(e){console.error(e);alert('Failed to remove process')}};
async function saveSettings(){const btn=$('save-settings-btn');const msg=$('settings-save-msg');const ws=Math.max(1,parseInt($('ws-interval').value||'5',10));const limit=Math.max(1,parseInt($('ui-conn-limit').value||'20',10));const type=$('upstream-type').value;const address=$('upstream-addr').value.trim();const port=parseInt($('upstream-port').value||'0',10);const buffer=Math.min(1048576,Math.max(32768,parseInt($('relay-buffer-size').value||'262144',10)));if(!address||port<1||port>65535){alert('Invalid upstream address or port');return}btn.innerText='Saving...';try{const rs=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ws_refresh_interval:ws,ui_conn_limit:limit})});const ru=await fetch('/api/upstream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,address,port})});const rp=await fetch('/api/performance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({buffer_size:buffer,tcp_nodelay:true,tcp_keep_alive:true,keep_alive_period:15,tcp_linger:-1})});if(!rs.ok||!ru.ok||!rp.ok)throw new Error('save failed');uiConnLimit=limit;msg.style.display='inline-block';setTimeout(()=>msg.style.display='none',2500)}catch(e){console.error(e);alert('Failed to save settings')}finally{btn.innerText='Save Settings'}}
function ok(r){if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
