let uiConnLimit=20, pollTimer=null, whitelist=new Set(), pidSort='none', currentView='status';
function $(id){return document.getElementById(id)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||''))}
function init(){bindNav();bindActions();loadSettings();loadUpstream();loadPerformance();loadProcesses();refreshStatus();updateStatusPolling();document.addEventListener('visibilitychange',updateStatusPolling)}
function bindNav(){const views={status:'view-status',processes:'view-processes',settings:'view-settings'},nav={status:'nav-status',processes:'nav-processes',settings:'nav-settings'};for(const k of Object.keys(nav))$(nav[k])?.addEventListener('click',e=>{e.preventDefault();currentView=k;for(const x of Object.keys(nav)){$(nav[x])?.classList.toggle('active',x===k);$(views[x]).style.display=x===k?'block':'none'};$('page-title').textContent=k==='status'?'代理 / 直连状态':k==='processes'?'进程白名单':'设置';if(k==='processes')loadProcesses();if(k==='settings'){loadUpstream();loadPerformance()}if(k==='status')refreshStatus();updateStatusPolling();history.replaceState(null,'',`#${k}`)})}
function bindActions(){$('add-process-btn')?.addEventListener('click',addProcess);$('process-input')?.addEventListener('keydown',e=>{if(e.key==='Enter')addProcess()});$('save-settings-btn')?.addEventListener('click',saveSettings);$('active-only')?.addEventListener('change',refreshStatus);$('pid-sort')?.addEventListener('click',togglePidSort);$('pid-sort')?.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')togglePidSort()})}
function startStatusPolling(){if(pollTimer||currentView!=='status'||document.visibilityState==='hidden')return;pollTimer=setInterval(refreshStatus,3000)}
function stopStatusPolling(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}}
function updateStatusPolling(){if(currentView==='status'&&document.visibilityState!=='hidden')startStatusPolling();else stopStatusPolling()}
async function json(url,options){const r=await fetch(url,options);if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function refreshStatus(){try{const d=await json('/api/status');$('sys-pid').textContent=d.pid??'--';$('proxy-programs').textContent=d.proxy_programs??0;$('direct-programs').textContent=d.direct_programs??0;$('proxy-connections').textContent=d.proxy_connections??0;$('direct-connections').textContent=d.direct_connections??0;setEngineState(d.status==='running');renderStatuses(Array.isArray(d.processes)?d.processes:[])}catch(e){setEngineState(false)}}
function setEngineState(ok){$('engine-status').classList.toggle('green',ok);$('engine-status').classList.toggle('red',!ok);$('engine-status-text').textContent=ok?'运行中':'未连接'}
function togglePidSort(){pidSort=pidSort==='none'?'asc':pidSort==='asc'?'desc':'none';updatePidSortIndicator();refreshStatus()}
function updatePidSortIndicator(){const th=$('pid-sort');if(!th)return;th.textContent=`PID${pidSort==='asc'?' ↑':pidSort==='desc'?' ↓':' ↕'}`;th.title=pidSort==='none'?'按 PID 从小到大排序':pidSort==='asc'?'按 PID 从大到小排序':'恢复按连接数排序'}
function renderStatuses(list){const body=$('process-status-list');const rows=($('active-only')?.checked!==false)?list.filter(x=>Number(x.connections)>0):list;if(!rows.length){body.innerHTML='<tr><td colspan="6" class="empty">当前没有检测到活动网络连接。</td></tr>';updatePidSortIndicator();return}if(pidSort==='asc')rows.sort((a,b)=>Number(a.pid||0)-Number(b.pid||0));else if(pidSort==='desc')rows.sort((a,b)=>Number(b.pid||0)-Number(a.pid||0));else rows.sort((a,b)=>Number(b.connections||0)-Number(a.connections||0));updatePidSortIndicator();body.innerHTML=rows.map(x=>{const proxy=x.status==='proxy',name=String(x.process||''),isAdded=whitelist.has(name.toLowerCase());const targets=Array.isArray(x.targets)&&x.targets.length?x.targets.map(esc).join('<br>'):'-';let action=isAdded?'<span class="muted">已在白名单</span>':`<button class="quick-add" data-process="${esc(name)}">加入白名单</button>`;return `<tr><td><strong>${esc(name)}</strong></td><td>${esc(x.pid)}</td><td><span class="state ${proxy?'proxy':'direct'}">${proxy?'代理':'直连'}</span></td><td>${esc(x.connections)}</td><td class="targets">${targets}</td><td>${action}</td></tr>`}).join('');body.querySelectorAll('.quick-add').forEach(btn=>btn.addEventListener('click',()=>quickAddProcess(btn.dataset.process)))}
async function quickAddProcess(process){if(!process||process.toLowerCase()==='unknown')return alert('无法添加未知进程。');if(whitelist.has(process.toLowerCase()))return;try{const d=await json('/api/process-whitelist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({process})});setWhitelist(d.processes||[]);await loadProcesses();await refreshStatus()}catch(e){alert('加入白名单失败：'+e.message)}}
function setWhitelist(list){whitelist=new Set((Array.isArray(list)?list:[]).map(p=>String(p).trim().toLowerCase()).filter(Boolean))}
async function loadSettings(){try{const d=await json('/api/settings');uiConnLimit=Math.max(1,Number(d.ui_conn_limit||20))}catch(e){}}
async function loadUpstream(){try{const d=await json('/api/upstream');$('upstream-type').value=d.type||'socks5';$('upstream-addr').value=d.address||'127.0.0.1';$('upstream-port').value=d.port||9192}catch(e){}}
async function loadPerformance(){try{const d=await json('/api/performance');const n=Math.min(1048576,Math.max(32768,Number(d.buffer_size||262144)));$('relay-buffer-size').value=String(n)}catch(e){}}
async function loadProcesses(){try{const d=await json('/api/process-whitelist');setWhitelist(d.processes||[]);renderProcesses(Array.isArray(d.processes)?d.processes:[])}catch(e){$('process-list').innerHTML=''}}
function renderProcesses(list){const box=$('process-list'),empty=$('process-empty');if(!list.length){box.innerHTML='';empty.style.display='block';return}empty.style.display='none';box.innerHTML=list.map(p=>`<div class="process-item"><strong>${esc(p)}</strong><button class="danger" onclick="removeProcess('${esc(p)}')">删除</button></div>`).join('')}
async function addProcess(){const input=$('process-input'),p=input?.value.trim();if(!p)return;try{const d=await json('/api/process-whitelist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({process:p})});input.value='';setWhitelist(d.processes||[]);renderProcesses(d.processes||[]);refreshStatus()}catch(e){alert('添加失败：'+e.message)}}
window.removeProcess=async function(p){try{const d=await json('/api/process-whitelist',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({process:p})});setWhitelist(d.processes||[]);renderProcesses(d.processes||[]);refreshStatus()}catch(e){alert('删除失败：'+e.message)}};
async function saveSettings(){const btn=$('save-settings-btn'),msg=$('settings-save-msg');const type=$('upstream-type').value,address=$('upstream-addr').value.trim(),port=Number($('upstream-port').value),buffer=Math.min(1048576,Math.max(32768,Number($('relay-buffer-size').value||262144)));if(!address||port<1||port>65535){alert('请输入有效的代理地址和端口');return}btn.disabled=true;btn.textContent='保存中...';try{const ru=await json('/api/upstream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,address,port})});if(ru.status!=='ok')throw new Error('代理设置保存失败');const rp=await json('/api/performance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({buffer_size:buffer})});if(rp.status!=='ok')throw new Error('Buffer 设置保存失败');$('relay-buffer-size').value=String(rp.buffer_size||buffer);msg.style.display='inline';setTimeout(()=>msg.style.display='none',2500)}catch(e){alert('保存失败：'+e.message)}finally{btn.disabled=false;btn.textContent='保存设置'}}
document.addEventListener('DOMContentLoaded',init);
